#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <Pipes.h>
#include <SocketLib.h>
void global_storage_initializer_();
void inputPort_1_Daemon();
void inputPort_2_Daemon();
void inputPort_3_Daemon();
void inputPort_4_Daemon();
void outputPort_1_Daemon();
void outputPort_2_Daemon();
void outputPort_3_Daemon();
void outputPort_4_Daemon();
